server.port=8080
spring.application.name=nail-studio-api

# Configuração do Banco de Dados (Supabase PostgreSQL)
spring.datasource.url=jdbc:postgresql://db.jstxwuitdwirwqxqebmc.supabase.co:5432/postgres
spring.datasource.username=postgres
spring.datasource.password=nzzMC7OKnQ87oLgZ

# Configurações do JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect